apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: {{ .Values.database.credentials.postgresuser | b64enc | quote}}
  password: {{ .Values.database.credentials.postgrespasswd | b64enc | quote}}
