# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  flaskapp: jaiganeshjk/flask-app:latest
  flaskvue: jaiganeshjk/flask-vue:latest
  flaskdb: jaiganeshjk/flask-db:latest
database:
  volume:
    storageClassName: null
    resourceRequests:
      storage: 20Gi
    accessModes: [ "ReadWriteOnce" ]
  port:
    defaultPort: 5432
  credentials:
    postgresuser: postgres
    postgrespasswd: pleasechangeme
