apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: {{ .Values.database.port.defaultPort }}
    protocol: TCP
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    service: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
