apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-import-job
  namespace:  {{ .Release.Namespace }}
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: {{ .Values.image.flaskimport }}
        name: postgres-import-job
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: POSTGRES_DB
            value: books
        resources: {}
      restartPolicy: Never
status: {}
