apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-import-job
  namespace: bookshelf-app
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: jaiganeshjk/flask-import:latest
        name: postgres-import-job
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: POSTGRES_DB
            value: books
        resources: {}
      restartPolicy: Never
status: {}
