apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: flask
spec:
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    service: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
