apiVersion: v1
kind: Service
metadata:
  name: flask-vue
  labels:
    service: flask-vue
  name: flask-vue
spec:
  selector:
    app: flask-vue
  ports:
  - port: 8080
    targetPort: 8080
    name: vue
  - port: 5000
    targetPort: 5000
    name: flask
