# base image
FROM docker.io/bitnami/postgresql:11.11.0-debian-10-r9

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

WORKDIR /tmp/
# copy import sql query and entrypoint script
COPY *.sql entrypoint.sh /tmp/

RUN chmod -R 775 /tmp && chmod +x /tmp/entrypoint.sh

ENTRYPOINT [ "./tmp/entrypoint.sh" ]
