# base image
FROM alpine

# install netcat
RUN apk --update add postgresql-client

WORKDIR /tmp/
# copy import sql query and entrypoint script
COPY *.sql entrypoint.sh /tmp/

RUN chmod -R 775 /tmp && chmod +x /tmp/entrypoint.sh

ENTRYPOINT [ /tmp/entrypoint.sh ]
